scom: Fix access to lseek64()
A build error, included below, occurs when building for 64-bit PowerPC
with musl libc. Since we explicitly use the 64-bit lseek64() API, we can
simply replace the _FILE_OFFSET_BITS define (i.e. make off_t 64-bits)
with _LARGEFILE64_SOURCE (i.e. make 64-bit API available).

scom.c:38:8: error: unknown type name 'off64_t'
   38 | static off64_t xscom_mangle_addr(off64_t addr)
      |        ^~~~~~~
scom.c:38:34: error: unknown type name 'off64_t'; did you mean 'off_t'?
   38 | static off64_t xscom_mangle_addr(off64_t addr)
      |                                  ^~~~~~~
      |                                  off_t
scom.c: In function 'open_and_seek':
scom.c:58:9: error: unknown type name 'off64_t'; did you mean 'off_t'?
   58 |         off64_t offset = xscom_mangle_addr(scom);
      |         ^~~~~~~
      |         off_t
scom.c:58:26: error: implicit declaration of function 'xscom_mangle_addr' [-Werror=implicit-function-declaration]
   58 |         off64_t offset = xscom_mangle_addr(scom);
      |                          ^~~~~~~~~~~~~~~~~
scom.c:68:13: error: implicit declaration of function 'lseek64'; did you mean 'lseek'? [-Werror=implicit-function-declaration]
   68 |         if (lseek64(*fd, offset, SEEK_SET) == (off_t)-1) {
      |             ^~~~~~~
      |             lseek
scom.c:69:42: error: format '%jd' expects argument of type 'intmax_t', but argument 3 has type 'int' [-Werror=format=]
   69 |                 fprintf(stderr, "lseek(%jd): %s\n", offset, strerror(errno));
      |                                        ~~^          ~~~~~~
      |                                          |          |
      |                                          long int   int
      |                                        %d
cc1: all warnings being treated as errors

Signed-off-by: Aaron Sierra <aaron@bubbl-tek.com>